name: flutter_coffee_app
description: "This is the milano coffee app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.1.1
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  dio: ^5.8.0+1
  retrofit: ^4.7.0
  firebase_core: ^3.12.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  json_annotation: ^4.9.0
  native_dio_adapter: ^1.5.0
  loading_indicator: any
  cached_network_image: any 
  mobile_scanner: ^7.0.1
  flutter_map: any 
  latlong2: any 
  geolocator: any
  equatable: any

 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: any
  build_runner: any
  json_serializable: any
  
  

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/ 
