// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9tFi1rFhu0zg-9AmkWwEX8b1FkXvWyOU',
    appId: '1:555308465221:web:638790152a51aa12c6372c',
    messagingSenderId: '555308465221',
    projectId: 'fir-sample-for-intern',
    authDomain: 'fir-sample-for-intern.firebaseapp.com',
    storageBucket: 'fir-sample-for-intern.firebasestorage.app',
    measurementId: 'G-RNTD400TH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_zASgSjCBcIKvQIKZeZdkWRev7KAuc4s',
    appId: '1:555308465221:android:bca6d2d7b0c3d1d9c6372c',
    messagingSenderId: '555308465221',
    projectId: 'fir-sample-for-intern',
    storageBucket: 'fir-sample-for-intern.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-vFLWrXZEzCxfN5FbTFcI3561NeI2qpg',
    appId: '1:555308465221:ios:29426ae7f0be95dec6372c',
    messagingSenderId: '555308465221',
    projectId: 'fir-sample-for-intern',
    storageBucket: 'fir-sample-for-intern.firebasestorage.app',
    androidClientId: '555308465221-mie19b1idm1ct5kgjmf9f5lvuq2ilmdq.apps.googleusercontent.com',
    iosClientId: '555308465221-n4r98814ag2p385qd7k6bihv1kf2mnjv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCoffeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-vFLWrXZEzCxfN5FbTFcI3561NeI2qpg',
    appId: '1:555308465221:ios:29426ae7f0be95dec6372c',
    messagingSenderId: '555308465221',
    projectId: 'fir-sample-for-intern',
    storageBucket: 'fir-sample-for-intern.firebasestorage.app',
    androidClientId: '555308465221-mie19b1idm1ct5kgjmf9f5lvuq2ilmdq.apps.googleusercontent.com',
    iosClientId: '555308465221-n4r98814ag2p385qd7k6bihv1kf2mnjv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCoffeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9tFi1rFhu0zg-9AmkWwEX8b1FkXvWyOU',
    appId: '1:555308465221:web:f559614be45ab187c6372c',
    messagingSenderId: '555308465221',
    projectId: 'fir-sample-for-intern',
    authDomain: 'fir-sample-for-intern.firebaseapp.com',
    storageBucket: 'fir-sample-for-intern.firebasestorage.app',
    measurementId: 'G-BP9YLJNNJ1',
  );
}
